### ISSUE TITLE
Audio_feat_seq and text_feat_seq not uniform in the second dimension

### ISSUE THREAD

**Issue by Shedima** [UttaranB127/speech2affective_gestures#17]
Hello，When I retrained this  model，the input of WavEncoder is [512*36327], the output is [512*10*32], the input of TextEncoderTCN is [512*34], the output is [512*34*32], it can be seen that the outputs of the two encoders is different in the second dimension, so it cannot be concat. How can I solve this problem?

**Comment by UttaranB127** [comment]
Hi, may I know the python command you're issuing?
