### ISSUE TITLE
Where is the "outputs/embedding_net.pth.tar"?

### ISSUE THREAD

**Issue by Talegqz** [UttaranB127/speech2affective_gestures#3]
I find too many bugs in this repo, such as absoulte path.
And I could not find the file "outputs/embedding_net.pth.tar" in **net/embedding_space_evaluator.py, line 24**.
Could you check the code and make sure that it is can run following the README?

**Comment by zf223669** [comment]
So do I

**Comment by UttaranB127** [comment]
Thanks for locating this bug! I have added a link to the [pre-trained weights of the embedding network](https://drive.google.com/file/d/17Fmk7lzyWhALXdmGW7hLNejEAFab8Tfr/view?usp=sharing) in the readme.
