### ISSUE TITLE
main_v2.py: error: the following arguments are required: -c/--config

### ISSUE THREAD

**Issue by zf223669** [UttaranB127/speech2affective_gestures#4]
Dear Sir:
 I run the main-v2.py with no arguments, it showed an error below:
main_v2.py: error: the following arguments are required: -c/--config
how could i fix it?
Thank you

**Comment by UttaranB127** [comment]
Please provide a path to the config file in the command line input. For our experiments, we used [multimodal_context_v2.yml](https://github.com/UttaranB127/speech2affective_gestures/blob/master/config/multimodal_context_v2.yml)
