### ISSUE TITLE
Baseline trimodal_gen model

### ISSUE THREAD

**Issue by cjerry1243** [UttaranB127/speech2affective_gestures#6]
Hi, 
Thanks for the fantastic work. 

Would you mind sharing with us your "trimodal_gen.pth.tar" pretrained model? I tried to use the one provided in the trimodal repo, but it doesn't work here. The stat_dict does not match.

I would like to do some comparisons in the research.

**Comment by UttaranB127** [comment]
Thanks for your interest in our work! The same issue was raised in issue #5, I have attached the downloadable links there.
