### ISSUE TITLE
Output pose length does not match the input audio

### ISSUE THREAD

**Issue by cjerry1243** [UttaranB127/speech2affective_gestures#9]
Hi,

I am wondering why we have to divide the word and audio into several sequences during inference.
That somehow results in shorter output pose than input audio. Is there a way to fix that?

**Comment by UttaranB127** [comment]
Hi, we did the subdivision following prior work, to keep our comparisons fair. As a result, if the clip length is not an exact multiple of the subdivision length, the final portion is dropped from the generation pipeline. You can change this behavior by changing the value of `unit_time`. I have added `unit_time` as a parameter in the method `render_clip` inside `processor_v2.py` to make this easier.

**Comment by cjerry1243** [comment]
How should I set the unit_time? the same as len(clip_audio) / 16000?

**Comment by cjerry1243** [comment]
I managed to fix them. Thank you.
